"""Single source of truth for PatchLab's public preset branding."""

from __future__ import annotations


APP_NAME = "PatchLab"
GENERATED_PRESET_TAGS = (APP_NAME, "Generated")
GENERATED_PRESET_DESCRIPTION = "Generated by PatchLab."


def generated_preset_name(synth: str | None = None) -> str:
    """Return an owner-neutral name for generated native preset metadata."""

    if synth == "serum1":
        return "PatchLab Serum 1 Match"
    if synth == "serum2":
        return "PatchLab Serum 2 Match"
    return "PatchLab Generated Preset"


def public_match_name(rank: int | None = None) -> str:
    """Return a fallback label when a retrieval result has no stored name."""

    return (
        f"PatchLab Library Match {int(rank)}"
        if rank is not None
        else "PatchLab Library Match"
    )


def display_match_name(name: object, rank: int | None = None) -> str:
    """Preserve an owned preset's real name, with a branded empty-name fallback."""

    value = str(name).strip() if name is not None else ""
    return value or public_match_name(rank)
