"""Single source of truth for PatchLab's public preset branding."""

from __future__ import annotations


APP_NAME = "PatchLab"
GENERATED_PRESET_TAGS = (APP_NAME, "Generated")
GENERATED_PRESET_DESCRIPTION = "Generated by PatchLab."


def generated_preset_name(synth: str | None = None) -> str:
    """Return an owner-neutral name for generated native preset metadata."""

    if synth == "serum1":
        return "PatchLab Serum 1 Match"
    if synth == "serum2":
        return "PatchLab Serum 2 Match"
    return "PatchLab Generated Preset"


def public_match_name(rank: int | None = None) -> str:
    """Return a source-name-free label for a library retrieval result."""

    return (
        f"PatchLab Library Match {int(rank)}"
        if rank is not None
        else "PatchLab Library Match"
    )
